.PHONY: clean All

All:
	@echo "----------Building project:[ JudgeServer - Debug ]----------"
	@$(MAKE) -f  "JudgeServer.mk"
clean:
	@echo "----------Cleaning project:[ JudgeServer - Debug ]----------"
	@$(MAKE) -f  "JudgeServer.mk" clean
